### ISSUE TITLE
マニュアルの説明不足と感じた点について

### ISSUE THREAD

**Issue by hiyakake** [amehuri/amehuri_tools#4]
こんにちは！
ツイートを拝見して、早速真冬ちゃんで試そうとマニュアルを見て試みましたが説明不足と感じる点がありissueを立てさせていただきます。

不明点は以下の通りです。

1、間引いた後、元のPhysBoneのスクリプトはどうすべきなのか？
2、推奨ツールのVRCQuestToolsのAvata Dynamics設定の画面では、生成されたPhysBoneだけ選択すれば良いのか？
3、結果を取り消したい場合は初めに作ったGameObjectを消すだけで良いのか？

**Comment by amehuri** [comment]
ツールのご利用およびマニュアルのご指摘ありがとうございます。
マニュアルのTipsにご指摘いただいた部分を追記しましたので、よろしければそちらもご確認ください。

> 1、間引いた後、元のPhysBoneのスクリプトはどうすべきなのか？ 

非破壊変換の場合は、VQT Platform GameObject RemoverまたはVQT Platform Component Removerを使用することを推奨しています。(破壊的変換であれば、コンポーネントを削除しても構いません。)

> 2、推奨ツールのVRCQuestToolsのAvata Dynamics設定の画面では、生成されたPhysBoneだけ選択すれば良いのか？ 

生成されたPBは必ず選択してください。間引いたPBのほかに、もとのPBの中にそのまま使いたいものがあればそれも選択します。
VQT Platform GameObject RemoverまたはVQT Platform Component Removerを使用して「Androidでは維持」が無効になっているPBはその設定が優先される(はず？)なので、どちらでも構いません。

> 3、結果を取り消したい場合は初めに作ったGameObjectを消すだけで良いのか？

はい。元のアバターの設定には特に変更を加えていないので、それを消せば元通りになります。
